### ISSUE TITLE
Demo or Screenshot

### ISSUE THREAD

**Issue by sepinali** [Erffun/JsonTree#2]
Hi Erffun, It's really a good component that you made, I can tell by surfing the code. It would be really great that if you can provide us with some screenshot or online demo of your componentn.

Thanks a lot

**Comment by sepinali** [comment]
Hi Erffun, I'm still waiting for screenshot or online demo of your project. hope to see them soon ;)
You really did a great job. 
Tnx (+x)

**Comment by Erffun** [comment]
Hi Sepinali,
Thanks for using my component
I create a demo page for this tree view at http://erffun.github.io/jsontree
 I do hope these page will be useful for you
